import { createBareServer } from "@nebula-services/bare-server-node";
import { createServer } from "http";
import Fastify from "fastify";
import fastifyStatic from "@fastify/static";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { server as wisp } from "@mercuryworkshop/wisp-js/server";

// transport assets
import { baremuxPath } from "@mercuryworkshop/bare-mux/node";
import { epoxyPath } from "@mercuryworkshop/epoxy-transport";
import { libcurlPath } from "@mercuryworkshop/libcurl-transport";
import { bareModulePath } from "@mercuryworkshop/bare-as-module3";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

/* ---------------- Bare Server ---------------- */

const bare = createBareServer("/bare/", {
	logErrors: true,
	blockLocal: false,
});

wisp.options.allow_loopback_ips = true;
wisp.options.allow_private_ips = true;

/* ---------------- Fastify ---------------- */

const fastify = Fastify({
	logger: false,
	serverFactory: (handler) => {
		return createServer()
			.on("request", (req, res) => {
				res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
				res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");

				if (bare.shouldRoute(req)) {
					bare.routeRequest(req, res);
				} else {
					handler(req, res);
				}
			})
			.on("upgrade", (req, socket, head) => {
				if (bare.shouldRoute(req)) {
					bare.routeUpgrade(req, socket, head);
				} else {
					wisp.routeRequest(req, socket, head);
				}
			});
	},
});

/* ---------------- Static Assets ---------------- */

// Scramjet UI (SPA)
fastify.register(fastifyStatic, {
	root: join(__dirname, "dist"),
	prefix: "/scram/",
	index: "index.html",
	decorateReply: false,
});

// Assets generated by build
fastify.register(fastifyStatic, {
	root: join(__dirname, "dist/assets"),
	prefix: "/assets/",
	decorateReply: false,
});

// Bare transports
fastify.register(fastifyStatic, {
	root: baremuxPath,
	prefix: "/baremux/",
	decorateReply: false,
});
fastify.register(fastifyStatic, {
	root: epoxyPath,
	prefix: "/epoxy/",
	decorateReply: false,
});
fastify.register(fastifyStatic, {
	root: libcurlPath,
	prefix: "/libcurl/",
	decorateReply: false,
});
fastify.register(fastifyStatic, {
	root: bareModulePath,
	prefix: "/baremod/",
	decorateReply: false,
});

/* ---------------- SPA Fallback ---------------- */

// SPA routing for Scramjet
fastify.get("/scram/*", async (_, reply) => {
	return reply.sendFile("index.html");
});

// Optional root health check
fastify.get("/", async (_, reply) => {
	reply.type("text/plain").send("Scramjet is running");
});

/* ---------------- Start Server ---------------- */

const PORT = Number(process.env.PORT) || 8080;

fastify.listen(
	{
		port: PORT,
		host: "0.0.0.0",
	},
	(err) => {
		if (err) {
			console.error(err);
			process.exit(1);
		}
		console.log(`Scramjet listening on 0.0.0.0:${PORT}`);
	}
);
